SchrodingersGat/lumberjack

- README.md
- src/series.cpp
- src/series.hpp
- test/test_series.cpp
> Implement binary search lookup for timestamps

- src/plot_widget.cpp
- src/plot_widget.hpp
> Track curve

- src/plot_widget.cpp
- src/plot_widget.hpp
Fixes https://github.com/SchrodingersGat/lumberjack/issues/26
> Add simple vertical markers

- src/mainwindow.cpp
- src/mainwindow.h
- src/plot_widget.cpp
- src/plot_widget.hpp
- src/widgets/timeline_widget.cpp
- src/widgets/timeline_widget.hpp
Fixes https://github.com/SchrodingersGat/lumberjack/issues/6
> Timeline view

- lumberjack.pro
- plugins/csv_importer.cpp
- plugins/csv_importer.hpp
- src/widgets/stats_widget.cpp
Fixes https://github.com/SchrodingersGat/lumberjack/issues/55
Reduces load speed of a 45MB sample file from ~1 minute to < 4 seconds!
> CSV processing speed

- src/plot_widget.cpp
Closes https://github.com/SchrodingersGat/lumberjack/issues/57
> zoom rubber band pen is changed based on background color of plot

- src/plot_widget.cpp
Closes https://github.com/SchrodingersGat/lumberjack/issues/40
> Update cursor shape based on keyboard modifier

- src/main.cpp
- src/mainwindow.cpp
- src/mainwindow.h
- Help option
- Version information option
- Option to load dummy data
> Adds command line flag parser

- src/mainwindow.cpp
- src/mainwindow.h
- src/widgets/dataview_tree.cpp
- src/widgets/dataview_tree.hpp
- src/widgets/dataview_widget.hpp
Closes https://github.com/SchrodingersGat/lumberjack/issues/34
> Remove data from plots when removed from data source list.

- lumberjack.pro
- src/lumberjack_debug.cpp
- src/lumberjack_debug.hpp
- src/main.cpp
- src/mainwindow.cpp
- src/mainwindow.h
- src/widgets/debug_widget.cpp
- src/widgets/debug_widget.hpp
- ui/debug_widget.ui
- ui/mainwindow.ui
Closes https://github.com/SchrodingersGat/lumberjack/issues/77
> Debug window

- src/mainwindow.cpp
Closes https://github.com/SchrodingersGat/lumberjack/issues/70
> Save / load window state

- src/mainwindow.cpp
- src/mainwindow.h
- ui/mainwindow.ui
Closes https://github.com/SchrodingersGat/lumberjack/issues/30
> Add facility for multiple plots

- lumberjack.pro
- plugins/csv_importer.cpp
- plugins/mavlink_importer.cpp
- plugins/mavlink_importer.hpp
- src/data_series.cpp
- src/main.cpp
- src/mainwindow.cpp
- src/widgets/debug_widget.cpp
Adds support for importing Mavlink / Ardupilot logs
> Mavlink log

- plugins/csv_importer.cpp
- plugins/csv_importer.hpp
- src/plot_widget.cpp
- ui/csv_import_options.ui
Adds ability to load in data which does not have a provided timestamp column
> Missing timestamp col

- .gitmodules
- lumberjack.pro
- src/fft_sampler.cpp
- src/fft_sampler.hpp
- src/fft_widget.cpp
- src/fft_widget.hpp
- src/lumberjack_version.hpp
- src/mainwindow.cpp
- src/mainwindow.h
- src/plot_curve.cpp
- src/plot_curve.hpp
- src/plot_widget.cpp
- src/plot_widget.hpp
- src/widgets/plot_sampler.cpp
- src/widgets/plot_sampler.hpp
- ui/mainwindow.ui
A separate window for displaying FFT data. Drag multiple curves onto the widget, and the FFT data is calculated and updated based on timescale data
> Adds FFT support

- src/plot_widget.cpp
> Add debug message

- BUILDING.md
- CONTRIBUTING.md
- README.md
- lumberjack.pro
- Update README.md
- Add BUILD.md
- Add CONTRIBUTING.md
> Update project documentation

- lumberjack.pro
- Better management of debug and release builds
- Ensure correct .dll files are copied across
> Improve .pro file

- src/mainwindow.cpp
- src/plot_widget.cpp
- src/plot_widget.hpp
- Closes https://github.com/SchrodingersGat/lumberjack/issues/108
> Allow setting plot title

- lumberjack.pro
- src/plot_curve.cpp
- src/plot_curve.hpp
- src/plot_widget.cpp
- src/widgets/plot_sampler.cpp
- src/widgets/plot_sampler.hpp
Minor efficiency improvements for sampling and rendering
> Resample updates

- src/main.cpp
Allows for opening a file with Lumberjack from a file browser using "Open with..."
> Change file command line option to positional arg

- src/mainwindow.cpp
Puts the new graph in a more sensible location
> Use splitDockWidget() for adding new graphs
